name: API tests Bookstore

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      # Установка зависимостей из package.json
      - name: Install deps
        run: npm ci

      # Запуск build из package.json (если он есть)
      - name: Run build
        run: npm run build --if-present

      # Запуск тестов
      - name: Run tests
        run: npm run test:coverage
        continue-on-error: true

      # Генерация отчета
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: report
          if-no-files-found: error
          path: ./jest-html-report

      # Загрузка покрытия
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          if-no-files-found: error
          path: ./coverage

      # Отправка нотификации в Telegram
      - name: Send notification to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TOKEN_TELEGRAM }}
          message: |
            ${{ github.workflow }} completed.
            
            See report: https://otus-qa-js-2022-11-sadovaya-hw13.pages.dev/report

      # Публикация отчета в Cloudflare Pages
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: ./jest-html-report
          githubToken: ${{ secrets.TOKEN_GITHUB }}
